### PR TITLE
Better form to check mention in command

### PR DESCRIPTION
**Pull request by Doc94**
In any cases the mention can be <ID> or <!ID> for this cases its better remove all characters and use only the ID, with this you can use the same "Command Class" in another bot instances.

### CODE REVIEW

**Comment by Vampire** [comment]
But that would also trigger in cases where there was not a mention of the bot user. Why should that be better? Why not simply check for both variants of mention?

**Comment by Doc94** [comment]
Well change the replace with check in all cases of mentions for avoid use how to message only the ID of the bot for trigger command.

**Comment by Vampire** [comment]
And now you should probably better combine those two commits into one and force-push. :-)
Would you mind doing it also for the other handlers?
With your PR the handlers would behave differently.

**Comment by Doc94** [comment]
The others two handlers use other form to check this, they generate the mention, and dont know if this issue happen in the another handlers.

**Comment by Vampire** [comment]
It does

**Comment by Bastian** [comment]
Hey,
thank you for the PR, but as this PR didn't fix the other two handlers as well, I fixed this myself.

**Pull request closed without merging**
